#!/usr/bin/env python3
from __future__ import annotations

import csv
import html
import os
import smtplib
import ssl
import sys
from email.message import EmailMessage
from pathlib import Path


def load_matches(path: str | Path) -> list[dict[str, str]]:
    path = Path(path)
    if not path.exists() or path.stat().st_size == 0:
        return []
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def _score(row: dict[str, str]) -> int:
    for key in ("total", "score"):
        try:
            return int(float(row.get(key, "0") or 0))
        except (TypeError, ValueError):
            pass
    return 0


def _num(row: dict[str, str], key: str) -> float:
    try:
        return float(row.get(key, "0") or 0)
    except (TypeError, ValueError):
        return 0.0


def _tier(score: int) -> tuple[str, str]:
    if score >= 85:
        return "Exceptional", "85–100"
    if score >= 75:
        return "Strong", "75–84"
    return "Review", "65–74"


def _why(row: dict[str, str], limit: int = 3) -> list[str]:
    """Return concise, score-grounded reasons without inventing posting details."""
    components = [
        (_num(row, "role_fit") / 30, "Target computational biology / bioinformatics role"),
        (_num(row, "domain_fit") / 25, "Strong scientific-domain match"),
        (_num(row, "technical_fit") / 20, "Strong technical overlap"),
        (_num(row, "operating_model_fit") / 15, "Applications / workflows / cross-functional product work"),
        (_num(row, "leadership_fit") / 10, "Technical / project / people leadership"),
    ]
    components.sort(key=lambda x: x[0], reverse=True)
    return [label for frac, label in components if frac >= 0.65][:limit]


def _group_rows(rows: list[dict[str, str]]):
    groups = [("Exceptional", []), ("Strong", []), ("Review", [])]
    lookup = dict(groups)
    for row in sorted(rows, key=_score, reverse=True):
        lookup[_tier(_score(row))[0]].append(row)
    return [(name, lookup[name]) for name, _ in groups if lookup[name]]


def build_plain_text(rows: list[dict[str, str]]) -> str:
    lines = [f"{len(rows)} new biotech job match(es) scored 65 or higher:\n"]
    for tier, group in _group_rows(rows):
        lines.append(f"{tier.upper()} FIT")
        lines.append("-" * (len(tier) + 4))
        for row in group:
            title = row.get("title", "Untitled role")
            company = row.get("company", "Unknown company")
            location = row.get("location", "") or "Location not listed"
            compensation = row.get("compensation", "") or "Not listed"
            url = row.get("url", "")
            why = " · ".join(_why(row))
            lines.append(f"{_score(row)} — {company} — {title}")
            lines.append(f"   {location} · Compensation: {compensation}")
            if why:
                lines.append(f"   Why: {why}")
            if url:
                lines.append(f"   {url}")
            lines.append("")
    lines.append("Generated by the private biotech-job-engine GitHub Actions workflow.")
    return "\n".join(lines)


def _card(row: dict[str, str]) -> str:
    score = _score(row)
    company = html.escape(row.get("company", "Unknown company"))
    title = html.escape(row.get("title", "Untitled role"))
    location = html.escape(row.get("location", "") or "Location not listed")
    compensation = html.escape(row.get("compensation", "") or "Not listed")
    url = html.escape(row.get("url", ""), quote=True)
    why = " · ".join(html.escape(x) for x in _why(row))
    link = f'<a href="{url}" style="font-weight:600">View posting</a>' if url else ""
    why_html = f'<div style="color:#555;margin-top:5px;font-size:13px"><strong>Why:</strong> {why}</div>' if why else ""
    return (
        "<div style='margin:0 0 10px 0;padding:11px 13px;border:1px solid #ddd;border-radius:7px'>"
        f"<div style='font-size:16px;font-weight:700'>{score} · {company}</div>"
        f"<div style='font-size:15px;margin-top:2px'>{title}</div>"
        f"<div style='color:#555;margin-top:5px;font-size:13px'>{location} &nbsp;·&nbsp; Compensation: {compensation}</div>"
        f"{why_html}"
        f"<div style='margin-top:6px;font-size:13px'>{link}</div></div>"
    )


def build_html(rows: list[dict[str, str]]) -> str:
    sections = []
    for tier, group in _group_rows(rows):
        _, band = _tier(_score(group[0]))
        sections.append(
            f"<h3 style='margin:22px 0 8px 0'>{tier} fit <span style='color:#777;font-size:13px;font-weight:400'>({band}) · {len(group)} role(s)</span></h3>"
            + "".join(_card(row) for row in group)
        )
    return (
        "<html><body style='font-family:Arial,sans-serif;max-width:760px;margin:auto;color:#222'>"
        f"<h2 style='margin-bottom:4px'>{len(rows)} new biotech job match(es)</h2>"
        "<p style='color:#555;margin-top:4px'>Newly discovered U.S.-eligible positions scoring 65 or higher, grouped by fit.</p>"
        + "".join(sections)
        + "<p style='color:#888;font-size:11px;margin-top:24px'>Generated by biotech-job-engine.</p></body></html>"
    )


def require(name: str) -> str:
    value = os.getenv(name, "").strip()
    if not value:
        raise RuntimeError(f"Missing required environment variable: {name}")
    return value


def send_email(rows: list[dict[str, str]]) -> None:
    if not rows:
        return
    host = require("SMTP_HOST")
    port = int(os.getenv("SMTP_PORT", "587"))
    username = require("SMTP_USERNAME")
    password = require("SMTP_PASSWORD")
    to_addr = require("EMAIL_TO")
    from_addr = os.getenv("EMAIL_FROM", "").strip() or username
    use_ssl = os.getenv("SMTP_USE_SSL", "false").strip().lower() in {"1", "true", "yes"}

    msg = EmailMessage()
    msg["Subject"] = f"Biotech job search: {len(rows)} new match(es)"
    msg["From"] = from_addr
    msg["To"] = to_addr
    msg.set_content(build_plain_text(rows))
    msg.add_alternative(build_html(rows), subtype="html")

    context = ssl.create_default_context()
    if use_ssl:
        with smtplib.SMTP_SSL(host, port, context=context, timeout=30) as server:
            server.login(username, password)
            server.send_message(msg)
    else:
        with smtplib.SMTP(host, port, timeout=30) as server:
            server.ehlo(); server.starttls(context=context); server.ehlo()
            server.login(username, password); server.send_message(msg)


def main() -> int:
    path = sys.argv[1] if len(sys.argv) > 1 else "output/new_matches.csv"
    rows = load_matches(path)
    if not rows:
        print("No new matches; no email sent.")
        return 0
    send_email(rows)
    print(f"Sent email for {len(rows)} new match(es).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
